# Generated by Django 3.2.12 on 2022-11-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=32, unique=True, verbose_name='用户id')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户id',
                'verbose_name_plural': '用户id',
                'ordering': ['ctime'],
            },
        ),
    ]
